# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 21:01
from __future__ import unicode_literals

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('specialuseform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='phone_evening',
            field=localflavor.us.models.PhoneNumberField(blank=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='phone_daytime',
            field=localflavor.us.models.PhoneNumberField(),
        ),
    ]
