# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-23 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialuseform', '0004_auto_20160922_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permit',
            name='id',
        ),
        migrations.AddField(
            model_name='permit',
            name='permit_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
