# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-23 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialuseform', '0005_auto_20160923_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
