# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialuseform', '0006_auto_20160923_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='status',
            field=models.CharField(choices=[('needs_approval', 'Needs Approval'), ('approved', 'Approved'), ('in_review', 'In Review'), ('not_approved', 'Rejected'), ('user_cancelled', 'User Cancelled')], default='needs_approval', max_length=100),
        ),
    ]
