# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('specialuseform', '0007_auto_20160927_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='organizer_address_2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='permit',
            name='state',
            field=localflavor.us.models.USStateField(),
        ),
    ]
