# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-28 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('specialuseform', '0008_auto_20160927_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='organizer_address_2',
            field=models.CharField(blank=True, help_text='(Optional)', max_length=250),
        ),
        migrations.AlterField(
            model_name='permit',
            name='participant_number',
            field=models.IntegerField(help_text='Number of Participants'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='phone_evening',
            field=localflavor.us.models.PhoneNumberField(blank=True, help_text='(Optional)'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='spectator_number',
            field=models.IntegerField(blank=True, help_text='(Optional) Number of Spectators'),
        ),
    ]
