# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-28 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialuseform', '0009_auto_20160928_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='participant_number',
            field=models.IntegerField(help_text='This is the number of participants who will partake in the event.', verbose_name='Number of Participants'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='spectator_number',
            field=models.IntegerField(blank=True, help_text='(Optional) If your event will have spectators (such as at a sporting event), please note how many additional people will be spectators.', verbose_name='Number of Spectators'),
        ),
    ]
