# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialuseform', '0009_auto_20160929_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='permit_holder_2_name',
            field=models.CharField(help_text='Name of Permit Holder', max_length=250, blank=True),
        ),
    ]
