# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('specialuseform', '0010_auto_20160930_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Format: MM/DD/YYYY'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='participant_number',
            field=models.IntegerField(help_text='This is the number of people who will directly participate in the event.', verbose_name='Number of Participants'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Format: MM/DD/YYYY'),
        ),
    ]
