# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialuseform', '0010_auto_20160930_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='decision_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='participant_number',
            field=models.IntegerField(help_text='This is the number of people who will directly participate in the event.', verbose_name='Number of Participants'),
        ),
    ]
