# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-28 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialuseform', '0011_auto_20160928_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='permit_holder_name',
            field=models.CharField(help_text='Name of Permit Holder', max_length=250),
        ),
    ]
