# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialuseform', '0012_auto_20161006_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='status',
            field=models.CharField(choices=[('needs_approval', 'Needs Approval'), ('approved', 'Approved'), ('in_review', 'In Review'), ('not_approved', 'Not Approved'), ('user_cancelled', 'User Cancelled')], default='needs_approval', max_length=100),
        ),
    ]
