# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-29 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('specialuseform', '0012_auto_20160928_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='organizer_address_2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='permit',
            name='permit_holder_2_address_2',
            field=models.CharField(blank=True, max_length=250, verbose_name='Street Address 2'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='permit_holder_address_2',
            field=models.CharField(blank=True, max_length=250, verbose_name='Street Address 2'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='phone_evening',
            field=localflavor.us.models.PhoneNumberField(blank=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='spectator_number',
            field=models.IntegerField(blank=True, help_text='If your event will have spectators (such as at a sporting event), please note how many additional people will be spectators.', verbose_name='Number of Spectators'),
        ),
    ]
