# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialuseform', '0013_auto_20161209_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permit',
            old_name='status',
            new_name='permit_status',
        ),
        migrations.RenameField(
            model_name='permit',
            old_name='permit_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='permit',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='spectator_number',
            field=models.IntegerField(blank=True, help_text='If your event will have spectators (such as at a sporting event), please note how many additional people will be spectators', verbose_name='Number of Spectators'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
