# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialuseform', '0014_auto_20161215_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permit',
            old_name='organizer_address_1',
            new_name='applicant_address_1',
        ),
        migrations.RenameField(
            model_name='permit',
            old_name='organizer_address_2',
            new_name='applicant_address_2',
        ),
        migrations.RenameField(
            model_name='permit',
            old_name='city',
            new_name='applicant_city',
        ),
        migrations.RenameField(
            model_name='permit',
            old_name='email',
            new_name='applicant_email',
        ),
        migrations.RenameField(
            model_name='permit',
            old_name='phone_daytime',
            new_name='applicant_phone_daytime',
        ),
        migrations.RenameField(
            model_name='permit',
            old_name='phone_evening',
            new_name='applicant_phone_evening',
        ),
        migrations.RenameField(
            model_name='permit',
            old_name='state',
            new_name='applicant_state',
        ),
        migrations.RenameField(
            model_name='permit',
            old_name='zipcode',
            new_name='applicant_zipcode',
        ),
        migrations.AlterField(
            model_name='permit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
