# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialuseform', '0015_auto_20161215_1647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permit',
            new_name='NonCommercialUsePermit',
        ),
    ]
